[package]
name = "vault-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
argon2 = "0.5"
aes-gcm = "0.10"
uuid = { version = "1", features = ["v4", "serde"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
